export enum IncidentSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum IncidentStatus {
  DRAFT = 'DRAFT',
  REPORTED = 'REPORTED',
  CLASSIFIED = 'CLASSIFIED',
  INVESTIGATION_IN_PROGRESS = 'INVESTIGATION_IN_PROGRESS',
  RCA_SUBMITTED = 'RCA_SUBMITTED',
  CAPA_PLANNING = 'CAPA_PLANNING',
  CAPA_EXECUTION = 'CAPA_EXECUTION',
  VERIFICATION_PENDING = 'VERIFICATION_PENDING',
  STATUTORY_REVIEW = 'STATUTORY_REVIEW',
  FINAL_APPROVAL_PENDING = 'FINAL_APPROVAL_PENDING',
  CLOSED = 'CLOSED',
}

export enum IncidentClassificationType {
  NEAR_MISS = 'NEAR_MISS',
  FIRST_AID = 'FIRST_AID',
  MEDICAL_TREATMENT = 'MEDICAL_TREATMENT',
  LOST_TIME_INJURY = 'LOST_TIME_INJURY',
  FATALITY = 'FATALITY',
  PROPERTY_DAMAGE = 'PROPERTY_DAMAGE',
  ENVIRONMENTAL_RELEASE = 'ENVIRONMENTAL_RELEASE',
}

export enum CapaStatus {
  DRAFT = 'DRAFT',
  ASSIGNED = 'ASSIGNED',
  IN_PROGRESS = 'IN_PROGRESS',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  VERIFIED = 'VERIFIED',
  CLOSED = 'CLOSED',
  OVERDUE = 'OVERDUE',
}

export enum CapaType {
  CORRECTIVE = 'CORRECTIVE',
  PREVENTIVE = 'PREVENTIVE',
}
