/**
 * Canonical Enterprise Permissions for Kenzo EHS Platform
 * Naming convention: MODULE.ACTION
 */
export const Permissions = {
  // Identity & Administration
  USER_CREATE: "USER.CREATE",
  USER_READ: "USER.READ",
  USER_UPDATE: "USER.UPDATE",
  USER_DELETE: "USER.DELETE",
  ROLE_ASSIGN: "ROLE.ASSIGN",
  ORGANIZATION_MANAGE: "ORGANIZATION.MANAGE",
  PLANT_MANAGE: "PLANT.MANAGE",
  DEPARTMENT_MANAGE: "DEPARTMENT.MANAGE",

  // HIRA (Hazard Identification & Risk Assessment)
  HIRA_CREATE: "HIRA.CREATE",
  HIRA_READ: "HIRA.READ",
  HIRA_UPDATE: "HIRA.UPDATE",
  HIRA_SUBMIT: "HIRA.SUBMIT",
  HIRA_REVIEW: "HIRA.REVIEW",
  HIRA_APPROVE: "HIRA.APPROVE",
  HIRA_REJECT: "HIRA.REJECT",
  HIRA_OVERRIDE_UNACCEPTABLE: "HIRA.OVERRIDE_UNACCEPTABLE",
  HIRA_ACTIVATE: "HIRA.ACTIVATE",
  HIRA_ARCHIVE: "HIRA.ARCHIVE",

  // Incidents
  INCIDENT_CREATE: "INCIDENT.CREATE",
  INCIDENT_READ: "INCIDENT.READ",
  INCIDENT_UPDATE: "INCIDENT.UPDATE",
  INCIDENT_CLASSIFY: "INCIDENT.CLASSIFY",
  INCIDENT_INVESTIGATE: "INCIDENT.INVESTIGATE",
  INCIDENT_SUBMIT: "INCIDENT.SUBMIT",
  INCIDENT_APPROVE: "INCIDENT.APPROVE",
  INCIDENT_CLOSE: "INCIDENT.CLOSE",
  INCIDENT_STATUTORY_FILE: "INCIDENT.STATUTORY_FILE",

  // RCA (Root Cause Analysis: 5-Why, Fishbone)
  RCA_CREATE: "RCA.CREATE",
  RCA_UPDATE: "RCA.UPDATE",
  RCA_SUBMIT: "RCA.SUBMIT",
  RCA_APPROVE: "RCA.APPROVE",

  // CAPA (Corrective and Preventive Action)
  CAPA_CREATE: "CAPA.CREATE",
  CAPA_READ: "CAPA.READ",
  CAPA_ASSIGN: "CAPA.ASSIGN",
  CAPA_UPDATE: "CAPA.UPDATE",
  CAPA_EXECUTE: "CAPA.EXECUTE",
  CAPA_VERIFY: "CAPA.VERIFY",
  CAPA_CLOSE: "CAPA.CLOSE",
  CAPA_REVIEW_EFFECTIVENESS: "CAPA.REVIEW_EFFECTIVENESS",

  // Permit To Work (PTW) & LOTO
  PTW_CREATE: "PTW.CREATE",
  PTW_READ: "PTW.READ",
  PTW_UPDATE: "PTW.UPDATE",
  PTW_SUBMIT: "PTW.SUBMIT",
  PTW_APPROVE: "PTW.APPROVE",
  PTW_CLOSE: "PTW.CLOSE",
  LOTO_APPLY: "LOTO.APPLY",
  LOTO_REMOVE: "LOTO.REMOVE",

  // Inspections & Audits
  INSPECTION_CREATE: "INSPECTION.CREATE",
  INSPECTION_READ: "INSPECTION.READ",
  INSPECTION_EXECUTE: "INSPECTION.EXECUTE",
  INSPECTION_SUBMIT: "INSPECTION.SUBMIT",
  INSPECTION_REVIEW: "INSPECTION.REVIEW",
  AUDIT_PERFORM: "AUDIT.PERFORM",
  AUDIT_READ: "AUDIT.READ",

  // Safety Observations (BBS)
  OBSERVATION_CREATE: "OBSERVATION.CREATE",
  OBSERVATION_READ: "OBSERVATION.READ",
  OBSERVATION_REVIEW: "OBSERVATION.REVIEW",
  OBSERVATION_CLOSE: "OBSERVATION.CLOSE",

  // Unified Actions
  ACTION_CREATE: "ACTION.CREATE",
  ACTION_READ: "ACTION.READ",
  ACTION_UPDATE: "ACTION.UPDATE",
  ACTION_VERIFY: "ACTION.VERIFY",
  ACTION_CLOSE: "ACTION.CLOSE",

  // Training & Competency
  TRAINING_MANAGE: "TRAINING.MANAGE",
  TRAINING_READ: "TRAINING.READ",

  // Contractor Management
  CONTRACTOR_MANAGE: "CONTRACTOR.MANAGE",
  CONTRACTOR_READ: "CONTRACTOR.READ",

  // Occupational Health
  HEALTH_READ: "HEALTH.READ",
  HEALTH_MANAGE: "HEALTH.MANAGE",

  // Environment & ESG
  ENVIRONMENT_MANAGE: "ENVIRONMENT.MANAGE",
  ENVIRONMENT_READ: "ENVIRONMENT.READ",

  // Emergency Management
  EMERGENCY_MANAGE: "EMERGENCY.MANAGE",
  EMERGENCY_READ: "EMERGENCY.READ",

  // Compliance & Legal Register
  COMPLIANCE_MANAGE: "COMPLIANCE.MANAGE",
  COMPLIANCE_READ: "COMPLIANCE.READ",

  // Reports & Analytics
  REPORTS_READ: "REPORTS.READ",

  // Audit Logs & Compliance
  AUDIT_LOG_READ: "AUDIT_LOG.READ",
} as const;

export type Permission = (typeof Permissions)[keyof typeof Permissions];
