/**
 * Fine-grained enterprise permissions formatted as RESOURCE.ACTION
 * Direct role string checks (e.g. if role === 'admin') are strictly forbidden.
 */
export const Permissions = {
  // Identity & Admin
  USER_CREATE: 'USER.CREATE',
  USER_READ: 'USER.READ',
  USER_UPDATE: 'USER.UPDATE',
  USER_DELETE: 'USER.DELETE',
  ROLE_ASSIGN: 'ROLE.ASSIGN',
  ORGANIZATION_MANAGE: 'ORGANIZATION.MANAGE',
  PLANT_MANAGE: 'PLANT.MANAGE',

  // HIRA
  HIRA_CREATE: 'HIRA.CREATE',
  HIRA_READ: 'HIRA.READ',
  HIRA_UPDATE: 'HIRA.UPDATE',
  HIRA_DELETE: 'HIRA.DELETE',
  HIRA_SUBMIT: 'HIRA.SUBMIT',
  HIRA_REVIEW: 'HIRA.REVIEW',
  HIRA_APPROVE: 'HIRA.APPROVE',
  HIRA_OVERRIDE_UNACCEPTABLE: 'HIRA.OVERRIDE_UNACCEPTABLE',
  HIRA_ACTIVATE: 'HIRA.ACTIVATE',
  HIRA_ARCHIVE: 'HIRA.ARCHIVE',

  // Incidents
  INCIDENT_CREATE: 'INCIDENT.CREATE',
  INCIDENT_READ: 'INCIDENT.READ',
  INCIDENT_UPDATE: 'INCIDENT.UPDATE',
  INCIDENT_CLASSIFY: 'INCIDENT.CLASSIFY',
  INCIDENT_ASSIGN_INVESTIGATION: 'INCIDENT.ASSIGN_INVESTIGATION',
  INCIDENT_INVESTIGATE: 'INCIDENT.INVESTIGATE',
  INCIDENT_APPROVE: 'INCIDENT.APPROVE',
  INCIDENT_CLOSE: 'INCIDENT.CLOSE',
  INCIDENT_STATUTORY_FILE: 'INCIDENT.STATUTORY_FILE',

  // RCA
  RCA_CREATE: 'RCA.CREATE',
  RCA_UPDATE: 'RCA.UPDATE',
  RCA_APPROVE: 'RCA.APPROVE',

  // CAPA
  CAPA_CREATE: 'CAPA.CREATE',
  CAPA_READ: 'CAPA.READ',
  CAPA_UPDATE: 'CAPA.UPDATE',
  CAPA_ASSIGN: 'CAPA.ASSIGN',
  CAPA_EXECUTE: 'CAPA.EXECUTE',
  CAPA_SUBMIT_EVIDENCE: 'CAPA.SUBMIT_EVIDENCE',
  CAPA_VERIFY: 'CAPA.VERIFY',
  CAPA_CLOSE: 'CAPA.CLOSE',
  CAPA_REVIEW_EFFECTIVENESS: 'CAPA.REVIEW_EFFECTIVENESS',

  // Work Control
  PTW_CREATE: 'PTW.CREATE',
  PTW_APPROVE: 'PTW.APPROVE',
  PTW_CLOSE: 'PTW.CLOSE',
  LOTO_APPLY: 'LOTO.APPLY',
  LOTO_REMOVE: 'LOTO.REMOVE',

  // Assurance
  INSPECTION_CREATE: 'INSPECTION.CREATE',
  INSPECTION_PERFORM: 'INSPECTION.PERFORM',
  AUDIT_PERFORM: 'AUDIT.PERFORM',
  AUDIT_LOG_READ: 'AUDIT_LOG.READ',
} as const;

export type Permission = (typeof Permissions)[keyof typeof Permissions];
