/**
 * Canonical 19 Enterprise Roles for Kenzo EHS Platform
 */
export enum UserRoleType {
  WORKER = "WORKER",
  CONTRACTOR_WORKMAN = "CONTRACTOR_WORKMAN",
  SUPERVISOR = "SUPERVISOR",
  DEPARTMENT_HEAD = "DEPARTMENT_HEAD",
  PERMIT_ISSUER = "PERMIT_ISSUER",
  SAFETY_OFFICER = "SAFETY_OFFICER",
  HSE_MANAGER = "HSE_MANAGER",
  PLANT_HEAD = "PLANT_HEAD",
  MAINTENANCE_HEAD = "MAINTENANCE_HEAD",
  TRAINER = "TRAINER",
  LD_MANAGER = "LD_MANAGER",
  ENVIRONMENT_MANAGER = "ENVIRONMENT_MANAGER",
  CONTRACTOR_COORDINATOR = "CONTRACTOR_COORDINATOR",
  OCCUPATIONAL_HEALTH_OFFICER = "OCCUPATIONAL_HEALTH_OFFICER",
  EMERGENCY_RESPONSE_COORDINATOR = "EMERGENCY_RESPONSE_COORDINATOR",
  INDUSTRIAL_HYGIENIST = "INDUSTRIAL_HYGIENIST",
  CORPORATE_HSE = "CORPORATE_HSE",
  ADMIN = "ADMIN",
  SYSTEM_ADMIN = "SYSTEM_ADMIN",
}

/**
 * Access Scope Boundaries
 */
export enum AccessScope {
  SYSTEM = "SYSTEM",
  ORGANIZATION = "ORGANIZATION",
  ALL_PLANTS = "ALL_PLANTS",
  OWN_PLANT = "OWN_PLANT",
  OWN_DEPARTMENT = "OWN_DEPARTMENT",
  OWN_AREA = "OWN_AREA",
  OWN_RECORDS = "OWN_RECORDS",
  ASSIGNED_RECORDS = "ASSIGNED_RECORDS",
}
