/**
 * 19 Operational Roles defined in Kenzo EHS Enterprise Architecture
 */
export enum UserRoleType {
  SUPER_ADMIN = 'SUPER_ADMIN',
  CORPORATE_HSE_HEAD = 'CORPORATE_HSE_HEAD',
  CORPORATE_HSE_MANAGER = 'CORPORATE_HSE_MANAGER',
  PLANT_HEAD = 'PLANT_HEAD',
  HSE_MANAGER = 'HSE_MANAGER',
  SAFETY_OFFICER = 'SAFETY_OFFICER',
  DEPARTMENT_HEAD = 'DEPARTMENT_HEAD',
  MAINTENANCE_HEAD = 'MAINTENANCE_HEAD',
  AREA_IN_CHARGE = 'AREA_IN_CHARGE',
  SHIFT_SUPERVISOR = 'SHIFT_SUPERVISOR',
  OPERATOR = 'OPERATOR',
  WORKER_REPRESENTATIVE = 'WORKER_REPRESENTATIVE',
  CONTRACTOR_SUPERVISOR = 'CONTRACTOR_SUPERVISOR',
  CONTRACTOR_WORKER = 'CONTRACTOR_WORKER',
  INVESTIGATION_LEAD = 'INVESTIGATION_LEAD',
  INVESTIGATION_MEMBER = 'INVESTIGATION_MEMBER',
  CAPA_OWNER = 'CAPA_OWNER',
  INDEPENDENT_VERIFIER = 'INDEPENDENT_VERIFIER',
  AUDITOR = 'AUDITOR',
}

/**
 * Access scope boundary for evaluation of permissions
 */
export enum AccessScope {
  GLOBAL = 'GLOBAL',
  ORGANIZATION = 'ORGANIZATION',
  ALL_PLANTS = 'ALL_PLANTS',
  OWN_PLANT = 'OWN_PLANT',
  OWN_DEPARTMENT = 'OWN_DEPARTMENT',
  OWN_AREA = 'OWN_AREA',
  ASSIGNED_ONLY = 'ASSIGNED_ONLY',
}
